language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
install:
- composer update
script:
- "php $OPTS ./vendor/bin/phpunit"
- "./vendor/bin/phpcs --standard=./phpcs.xml -n ./src/"
- php coverage-checker.php clover.xml 70
notifications:
  slack:
    secure: fwLiJFbxPCyY6+REN3XZ06RlffSVua3tW5Ih/p4xwp2KXNdcCldWCmziVhf65JGYaRU20M4HEOOcD+IpOI/IjpNHjF/+6OmtUGfkT9OfDCmuElqyq8UT6ck+xfb7FVtK42zkx0U3xC1qCclbFjY1Rht7vt5VnGN7Q3qJ3ax7mcM=
env:
  global:
  - secure: pLsfbkA35rpgq/YGgXGPnkjRyD5EHKJQSA4KPBuwkCkXa4X63eADFf5oZpphAIVJz7dSIb0J+iUNdziTtlb36A1ragAFSoa2EffDUB0ydIeIA9hDWE1ukHrOLHnfvGaFc1Q75tKWurAgxo1svM8NPuR6iK6r4S1wqpBvXqZUBag=
  - secure: oDuQ3vB1tzNiN7eG372FOnsQP6lzoB/iuGWC1VWwyLfqTXLN0iVe/bLw1RZ8MaIAB2G/1IqomA3l7Il8URTOi2ZgSQjcPPI3h7eWR1Box14fKnFV9c3kjqJ0novoTIibhM8gHsw0hsRs1wPEdzOdyTP9bVkvcaXcvizUbHwpQZc=
matrix:
  include:
  - hhvm
  env: OPTS="-v ResourceLimit.SocketDefaultTimeout=10"
